name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  GITHUB_TOKEN: ${{ secrets.GOACTION }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: $(( secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: 1.19

    - name: Build
      run: |
        sudo apt update && sudo apt install -y libpcap-dev
        go build -o ./phantomsocks-original
        go build -o ./phantomsocks-pcap -tags pcap
        go build -o ./phantomsocks-rawsocket -tags rawsocket
    - name: upload
      uses: ncipollo/release-action@v1
      with:
        artifacts: "phantomsocks-pcap,phantomsocks-original,phantomsocks-rawsocket"
        tag: v1.0
        token: ${{ secrets.GITHUB_TOKEN }}
