name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_arch: [aarch64, arm64, x86_64]
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: 1.19

    - name: Build
      run: |
        sudo apt update && sudo apt install -y libpcap-dev
        go build -o ./phantomsocks-original
        go build -o ./phantomsocks-pcap -tags pcap
        go build -o ./phantomsocks-rawsocket -tags rawsocket
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: linuxps-${{ matrix.target_arch }}
        path: ./phantomsocks*
        
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: 1.19

    - name: Build
      run: |
        go build -v ./...
        go build -v -tags pcap ./...
        go build -v -tags windivert ./...
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: winps-${{ matrix.target_arch }}
        path: ./phantomsocks*

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: 1.19

    - name: Build
      run: |
        go build -v ./...
        go build -v -tags pcap ./...
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: macps-${{ matrix.target_arch }}
        path: ./phantomsocks*

